<?

define('DEV_DEPLOYMENT_MODE',true);
define('MEDIA_ROOT',BASE_PATH.'/media/');
define('MEDIA_URL',WEB_FOLDER.'media/');

//Blog
define('TUMBLR_BLOG_URL','tudisco.tumblr.com');
define('TUMBLR_API_URL','http://api.tumblr.com/v2/blog/'.TUMBLR_BLOG_URL);
define('TUMBLR_API_KEY','[ENTER TUMBLR API KEY HERE, SEE TUMBLR SETUP INSTRUCTIONS]');

//Github
define('GITHUB_INTEGRATION_ENABLED',true);
define('GITHUB_CLIENT_ID','[ENTER GITHUB CLIENT ID HERE, SEE GITHUB SETUP INSTRUCTIONS]');
define('GITHUB_CLIENT_SECRET','[ENTER GITHUB CLIENT SECRET HERE, SEE GITHUB SETUP INSTRUCTIONS]');
define('GITHUB_ACCESS_TOKEN','[ENTER GITHUB ACCESS TOKEN HERE, SEE GITHUB SETUP INSTRUCTIONS]');
define('GITHUB_API_URL','https://api.github.com/');
define('GITHUB_OAUTH_AUTHORIZE_URL','https://github.com/login/oauth/authorize');
define('GITHUB_OAUTH_ACCESS_TOKEN_URL','https://github.com/login/oauth/access_token');

//Twitter
define('TWITTER_INTEGRATION_ENABLED',true);
define('TWITTER_API_URL','http://api.twitter.com/1/statuses/user_timeline.json?include_rts=false&exclude_replies=true&screen_name=');
define('TWITTER_CONSUMER_KEY','[ENTER TWITTER CONSUMER KEY HERE, SEE TWITTER SETUP INSTRUCTIONS]');
define('TWITTER_CONSUMER_SECRET','[ENTER TWITTER CONSUMER SECRET HERE, SEE TWITTER SETUP INSTRUCTIONS]');
define('TWITTER_USER_KEY','[ENTER TWITTER USER KEY HERE, SEE TWITTER SETUP INSTRUCTIONS]');
define('TWITTER_USER_SECRET','[ENTER TWITTER USER SECRET HERE, SEE TWITTER SETUP INSTRUCTIONS]');

//Instragram
define('INSTAGRAM_INTEGRATION_ENABLED',true);
define('INSTAGRAM_OAUTH_ENABLED',true);
define('INSTAGRAM_API_URL','https://api.instagram.com/v1/');
define('INSTAGRAM_ACCESS_TOKEN','[ENTER INSTAGRAM ACCESS TOKEN HERE, SEE INSTAGRAM SETUP INSTRUCTIONS]');
define('INSTAGRAM_USER_ID','[ENTER INSTAGRAM USER_ID HERE, SEE INSTAGRAM SETUP INSTRUCTIONS]');
define('INSTAGRAM_CLIENT_ID','[ENTER INSTAGRAM CLIENT_ID HERE, SEE INSTAGRAM SETUP INSTRUCTIONS]');
define('INSTAGRAM_CLIENT_SECRET','[ENTER INSTAGRAM CLIENT_SECRET HERE, SEE INSTAGRAM SETUP INSTRUCTIONS]');
define('INSTAGRAM_OAUTH_AUTHORIZE_URL','https://api.instagram.com/oauth/authorize');
define('INSTAGRAM_OAUTH_ACCESS_TOKEN_URL','https://api.instagram.com/oauth/access_token');


define('DRIBBBLE_INTEGRATION_ENABLED',true);



if(DEV_DEPLOYMENT_MODE){
	error_reporting(E_ERROR | E_WARNING | E_PARSE);
}else{
	error_reporting(0);
}
